version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: jhipsterdb
    ports:
      - "27017:27017"
    networks:
      - app-network

  jhipster:
    image: your-dockerhub-username/jhipster:mongodb
    container_name: jhipster-mongodb
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/jhipsterdb
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
